version: '3'
services:
  db:
    container_name: db
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: "pipedrive"
      MYSQL_USER: "pipedrive"
      MYSQL_PASSWORD: "pipedrive"
      MYSQL_ROOT_PASSWORD: "pipedrive"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    restart: always
    image: gcr.io/pipedrive-nagy/pipedrive:latest
    environment:
      PIPEDRIVE_TOKEN: "Your Pipedrive Token"
      DATABASE_HOST: "db"
    working_dir: /app
    ports:
      - "3000:3000"
    command: ["/usr/local/bin/wait-for-mysql.sh", "db:3306", "--", "./pipedrive"]
volumes:
  dbdata: